/* Original presidency expansion. Pure rules; accepts the existing simulation state. */
const ExecutiveSim=(()=>{
 const limit=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
 const BLOCS=[{id:'reform',name:'Reform caucus',seats:27,base:75,want:'A full-strength public program'},{id:'center',name:'Pragmatic center',seats:26,base:42,want:'Independent oversight and a credible rollout'},{id:'regional',name:'Regional coalition',seats:22,base:25,want:'Grants reaching smaller communities'},{id:'fiscal',name:'Budget hawks',seats:25,base:15,want:'A revenue source and spending discipline'}];
 const BILLS=[{id:'housing',name:'Homes for a New Generation Act',policy:'housing',metric:'housing',sponsor:'chen',regions:['coast','lakes'],cost:9,story:'Build affordable homes and unlock stalled local developments.'},{id:'grid',name:'Reliable Power Act',policy:'grid',metric:'energy',sponsor:'ruiz',regions:['plains','sunbelt'],cost:8,story:'Modernize the grid and protect communities from power failures.'},{id:'health',name:'Healthy Communities Act',policy:'insurance',metric:'health',sponsor:'chen',regions:['sunbelt','plains'],cost:10,story:'Expand coverage and bring clinical care to underserved communities.'},{id:'schools',name:'Opportunity in Every Classroom Act',policy:'teacher',metric:'schools',sponsor:'bell',regions:['lakes','coast'],cost:7,story:'Recruit teachers and rebuild aging school facilities.'}];
 const AMENDMENTS=[{id:'local',name:'Small-community grants',cost:3,detail:'Regional coalition +40 support; reform caucus +5. Adds 3 spending per quarter and extends benefits to every region.'},{id:'audit',name:'Independent oversight',cost:1,detail:'Pragmatic center +25; budget hawks +10. Adds 1 spending per quarter; protects construction from procurement failures.'},{id:'revenue',name:'Progressive revenue package',cost:0,detail:'Budget hawks +35; center +5; regional coalition −10. Raises the progressive tax setting one step when the bill passes.'}];
 const REGIONS=[{id:'coast',name:'Coastal cities',governor:'Governor Lena Park',industry:'Technology, ports and services',points:30,groups:['students','climate','civil'],offset:{housing:-8,jobs:4,energy:0,health:1}},{id:'lakes',name:'Great Lakes',governor:'Governor Marcus Reed',industry:'Manufacturing and freight',points:25,groups:['workers','business'],offset:{housing:1,jobs:-6,energy:0,health:0}},{id:'plains',name:'Plains & small towns',governor:'Governor Elena Ruiz',industry:'Agriculture and energy',points:20,groups:['rural','suburban'],offset:{housing:5,jobs:-1,energy:-4,health:-4}},{id:'sunbelt',name:'Sunbelt communities',governor:'Governor Isabel Santos',industry:'Construction, tourism and care',points:25,groups:['retirees','health','fiscal'],offset:{housing:-3,jobs:1,energy:-2,health:-5}}];
 const GOALS=[{id:'housing',name:'Make homes attainable',metric:'housing',target:52},{id:'health',name:'Improve public health',metric:'health',target:57},{id:'energy',name:'Keep the lights on',metric:'energy',target:62},{id:'schools',name:'Expand opportunity',metric:'schools',target:57},{id:'trust',name:'Restore public trust',metric:'trust',target:59},{id:'debt',name:'Control national debt',target:95}];
 const TEAM={chen:{competence:74,portfolio:'Housing & health',policies:['housing','rent','clinic','insurance'],deputy:'Dr. Nia Patel'},ruiz:{competence:70,portfolio:'Regional delivery',policies:['roads','grid','fossil'],deputy:'Governor Owen Hale'},brooks:{competence:80,portfolio:'Treasury',policies:['tax','corporate','sales'],deputy:'Alex Morgan'},bell:{competence:68,portfolio:'Congress & education',policies:['teacher','college','transparency'],deputy:'Leader Grace Kim'}};
 function initialize(s){if(s.executive)return s;const regions=Object.fromEntries(REGIONS.map(r=>[r.id,{...Object.fromEntries(Object.keys(r.offset).map(k=>[k,limit(s.metrics[k]+r.offset[k])])),goodwill:0,news:[],visited:-1}]));const inherited=BILLS.filter(b=>s.levels[b.policy]===4).map(b=>({id:b.id,status:'passed',amendments:[],lobbied:[],introduced:s.quarter,passed:s.quarter,lastVote:-1,attempts:0,progress:limit(Math.round(((s.implemented[b.policy]||2)-2)*50)),inherited:true}));s.executive={regions,bills:inherited,platform:null,cabinet:Object.fromEntries(Object.entries(TEAM).map(([id,t])=>[id,{competence:t.competence,status:'serving',strain:0,acting:false,lastAction:-1}])),opposition:{name:'Senator Adrian Vale',momentum:12,issue:'housing'},crises:[],encounters:[],started:s.quarter,mandate:0};return s;}
 function allowed(s){return !s.ended&&s.agendaChoice===null;}
 function result(detail){return {ok:true,detail};}function fail(reason){return {ok:false,reason};}
 function record(s,type,title,detail){s.history.push({quarter:s.quarter,type,title,detail});}
 function news(s,id,text){const r=s.executive.regions[id];r.news.unshift({quarter:s.quarter,text});r.news=r.news.slice(0,8);}
 function billDef(id){return BILLS.find(b=>b.id===id);}
 function activeBill(s){return s.executive.bills.find(b=>['draft','failed'].includes(b.status));}
 function platform(s,ids,signature){if(!allowed(s)||s.executive.platform)return fail('Your platform has already been set, or this quarter is closed.');if(new Set(ids).size!==3||ids.some(id=>!GOALS.some(g=>g.id===id))||!billDef(signature))return fail('Choose three distinct promises and one signature project.');s.executive.platform={goals:[...ids],signature,chosen:s.quarter};record(s,'mandate','Your public mandate',ids.map(id=>GOALS.find(g=>g.id===id).name).join(' · '));return result('Your mandate is on the record. Track it throughout your term.');}
 function propose(s,id){if(!allowed(s))return fail('File legislation before closing the quarter.');if(!billDef(id)||activeBill(s)||s.executive.bills.some(b=>b.id===id))return fail('Finish your active bill before proposing another; each act can be introduced once.');if(s.capital<2)return fail('Introducing legislation costs 2 political capital.');s.capital-=2;const bill={id,status:'draft',amendments:[],lobbied:[],introduced:s.quarter,lastVote:-1,attempts:0,progress:0};s.executive.bills.push(bill);record(s,'legislation','Bill introduced',billDef(id).name);return result('Bill introduced. Negotiate amendments and inspect the whip count before calling a vote.');}
 function votes(s,bill){const def=billDef(bill.id),bond=s.relationships[def.sponsor],team=s.executive.cabinet[def.sponsor];return BLOCS.map(bloc=>{let support=bloc.base+(bond-50)*.25+s.executive.mandate-s.executive.opposition.momentum*.15+(team.status==='resigned'?-10:0);if(bill.lobbied.includes(bloc.id))support+=15;
  if(bill.amendments.includes('local'))support+=({regional:40,reform:5}[bloc.id]||0);
  if(bill.amendments.includes('audit'))support+=({center:25,fiscal:10}[bloc.id]||0);
  if(bill.amendments.includes('revenue'))support+=({fiscal:35,center:5,regional:-10}[bloc.id]||0);
  const regionalBoost=Object.values(s.executive.regions).reduce((sum,r)=>sum+r.goodwill,0)/4;if(bloc.id==='regional')support+=regionalBoost;
  support=limit(support);return {...bloc,support:Math.round(support),yes:Math.round(bloc.seats*support/100)};});}
 function amend(s,id){const b=activeBill(s);if(!allowed(s)||!b||!AMENDMENTS.some(a=>a.id===id)||b.amendments.includes(id))return fail('That amendment is unavailable.');if(id==='revenue'&&s.levels.tax>=4)return fail('The progressive tax is already at its maximum. Seek a different coalition.');if(s.capital<1)return fail('Negotiating an amendment costs 1 political capital.');s.capital--;b.amendments.push(id);record(s,'legislation','Amendment accepted',AMENDMENTS.find(a=>a.id===id).name);return result('Amendment accepted. The whip count and cost forecast have changed.');}
 function lobby(s,id){const b=activeBill(s);if(!allowed(s)||!b||!BLOCS.some(g=>g.id===id)||b.lobbied.includes(id))return fail('That faction cannot be lobbied again for this bill.');if(s.location!=='oval'||slots(s)<1||s.capital<1)return fail('Lobbying requires an Oval Office appointment and 1 capital.');s.capital--;s.appointments.push({quarter:s.quarter,type:'lobby'});b.lobbied.push(id);record(s,'legislation','Congressional meeting',BLOCS.find(g=>g.id===id).name+' support increased.');return result('The faction agrees to support more of the package. Whip count updated.');}
 function vote(s){const b=activeBill(s);if(!allowed(s)||!b||b.lastVote===s.quarter)return fail('Call at most one floor vote on this bill each quarter.');if(s.capital<2)return fail('A floor vote costs 2 political capital.');s.capital-=2;b.lastVote=s.quarter;b.attempts++;b.rollcall=votes(s,b);b.yes=b.rollcall.reduce((n,g)=>n+g.yes,0);const def=billDef(b.id);if(b.yes>=51){b.status='passed';b.passed=s.quarter;s.levels[def.policy]=4;s.debt=limit(s.debt+def.cost,0,250);if(b.amendments.includes('revenue'))s.levels.tax=Math.min(4,s.levels.tax+1);s.metrics.trust=limit(s.metrics.trust+2);s.relationships[def.sponsor]=limit(s.relationships[def.sponsor]+5);record(s,'legislation',def.name+' passes',`${b.yes}–${100-b.yes}. Implementation begins next quarter. Initial debt +${def.cost}.`);return result(`Passed ${b.yes}–${100-b.yes}. The program now has legal authority; follow delivery on the national map.`);}b.status='failed';s.executive.opposition.momentum=limit(s.executive.opposition.momentum+6);record(s,'legislation',def.name+' defeated',`${b.yes}–${100-b.yes}. Amend the package and retry next quarter.`);return result(`Defeated ${b.yes}–${100-b.yes}. The opposition gains momentum. You can revise the bill and retry next quarter.`);}
 function slots(s){return Math.max(0,2-s.appointments.filter(a=>a.quarter===s.quarter).length);}
 function regionalView(s,id,basePoll){const def=REGIONS.find(r=>r.id===id),r=s.executive.regions[id],local=(r.housing-s.metrics.housing+r.jobs-s.metrics.jobs+r.health-s.metrics.health+r.energy-s.metrics.energy)/4;return {...def,...r,approval:Math.round(limit(basePoll+local*.55+r.goodwill,5,95))};}
 function election(s,basePoll){const regions=REGIONS.map(r=>regionalView(s,r.id,basePoll)),points=regions.filter(r=>r.approval>=50).reduce((n,r)=>n+r.points,0);return {points,regions:regions.map(r=>({id:r.id,name:r.name,approval:r.approval,points:r.points,won:r.approval>=50})),won:points>50};}
 function regionalVisit(s,id){const r=s.executive.regions[id];if(!allowed(s)||!r||s.location!=='aircraft'||slots(s)<1||s.capital<2||r.visited===s.quarter)return fail('A regional visit needs an Air Force One appointment, 2 capital, and an unvisited region this quarter.');s.capital-=2;s.debt=limit(s.debt+3,0,250);s.appointments.push({quarter:s.quarter,type:'regional'});r.visited=s.quarter;r.goodwill=limit(r.goodwill+3,-15,15);const key=['housing','jobs','energy','health'].sort((a,b)=>r[a]-r[b])[0];r[key]=limit(r[key]+2);const text=`Federal visit brings targeted ${key} assistance and a meeting with ${REGIONS.find(x=>x.id===id).governor}.`;news(s,id,text);record(s,'region',REGIONS.find(x=>x.id===id).name,text);return result('Visit completed. The weakest local service improves by 2; regional goodwill +3; debt +3.');}
 function modifier(s,group){if(!s.executive)return 0;const region=REGIONS.find(r=>r.groups.includes(group)),r=region&&s.executive.regions[region.id];return (r?(r.housing-s.metrics.housing+r.jobs-s.metrics.jobs+r.health-s.metrics.health+r.energy-s.metrics.energy)*.025+r.goodwill*.2:0)-s.executive.opposition.momentum*.035;}
 function spending(s){return s.executive?s.executive.bills.filter(b=>b.status==='passed').reduce((n,b)=>n+b.amendments.reduce((a,id)=>a+AMENDMENTS.find(x=>x.id===id).cost,0),0):0;}
 function staffFactor(s,policy){if(!s.executive)return 1;const id=Object.keys(TEAM).find(id=>TEAM[id].policies.includes(policy));if(!id)return 1;const p=s.executive.cabinet[id];return p.status==='resigned'?.55:.65+p.competence/200;}
 function teamAction(s,id,action){const p=s.executive.cabinet[id];if(!allowed(s)||!p||!['support','train','replace'].includes(action)||p.lastAction===s.quarter||slots(s)<1||s.location!=='oval')return fail('Team decisions need one Oval Office appointment per person per quarter.');const cost=action==='replace'?3:2;if(s.capital<cost)return fail(`This action costs ${cost} political capital.`);if(action!=='replace'&&p.status==='resigned')return fail('Appoint an acting replacement for this vacant role.');if(action==='replace'&&p.acting&&p.status!=='resigned')return fail('An acting replacement is already in place.');s.capital-=cost;s.appointments.push({quarter:s.quarter,type:'team'});p.lastAction=s.quarter;
  if(action==='support'){s.relationships[id]=limit(s.relationships[id]+10);p.strain=0;}
  if(action==='train')p.competence=limit(p.competence+10);
  if(action==='replace'){p.status='serving';p.acting=true;p.competence=68;p.strain=0;s.relationships[id]=50;}
  record(s,'cabinet','Government team',`${TEAM[id].portfolio}: ${action}.`);return result(action==='replace'?`${TEAM[id].deputy} takes over. Competence 68; relationship 50.`:action==='train'?'Delivery competence +10.':'Relationship +10. Immediate resignation pressure relieved.');}
 function person(s,base){const team=s.executive?.cabinet[base.id];return team?.acting?{...base,name:TEAM[base.id].deputy,initials:TEAM[base.id].deputy.split(' ').slice(-2).map(n=>n[0]).join('')}:base;}
 function crisisOptions(c){if(c.stage==='warning')return {title:'Storm watch: the coast',body:'Forecasters warn of a severe storm next quarter. Grid strength and preparation will determine the damage.',choices:[{id:'prepare',title:'Pre-position crews and supplies',detail:'Debt +4 · reduce storm damage by 5'},{id:'watch',title:'Monitor and conserve funds',detail:'No new cost · infrastructure must withstand the storm'}]};if(c.stage==='landfall')return {title:'Landfall and power failures',body:`Damage level ${c.damage}. Governors need a response before the next quarter.`,choices:[{id:'full',title:'Order rapid federal relief',detail:'Debt +8 · recover up to 7 local points · hurried contracts may trigger scrutiny'},{id:'target',title:'Coordinate audited state assistance',detail:'Debt +4 · recover up to 4 local points · lower procurement risk'}]};return {title:'The procurement investigation',body:'Auditors found irregularities in emergency or construction contracts. Your response will shape trust in the program.',choices:[{id:'publish',title:'Publish findings and replace contractors',detail:'Debt +2 · trust +2 · sponsor relationship −4'},{id:'defend',title:'Defend the current leadership',detail:'No cost · trust −4 · opposition momentum +6'}]};}
 function respondCrisis(s,id,choice){const c=s.executive.crises.find(c=>c.id===id);if(!allowed(s)||!c||c.stage==='resolved'||c.response||!crisisOptions(c).choices.some(x=>x.id===choice))return fail('This crisis response is unavailable.');c.response=choice;const r=s.executive.regions[c.region];if(choice==='prepare')s.debt=limit(s.debt+4,0,250);if(choice==='full'||choice==='target'){const amount=choice==='full'?7:4;s.debt=limit(s.debt+(choice==='full'?8:4),0,250);r.housing=limit(r.housing+Math.min(c.damage,amount));r.energy=limit(r.energy+Math.min(c.damage,amount));r.goodwill=limit(r.goodwill+2,-15,15);}
  if(choice==='publish'){s.debt=limit(s.debt+2,0,250);s.metrics.trust=limit(s.metrics.trust+2);s.relationships.chen=limit(s.relationships.chen-4);}
  if(choice==='defend'){s.metrics.trust=limit(s.metrics.trust-4);s.executive.opposition.momentum=limit(s.executive.opposition.momentum+6);}
  record(s,'crisis',crisisOptions(c).title,crisisOptions(c).choices.find(x=>x.id===choice).title);return result('Response recorded. The next quarterly report will show how the crisis develops.');}
 function encounterOptions(s,e){const issue=s.executive.opposition.issue;if(e.type==='debate')return {title:'The televised debate',speaker:e.stage===0?'Senator Adrian Vale':'Moderator: Jordan Ellis',question:e.stage===0?`“Your record on ${issue} is your weak point. Why should voters give you another term?”`:'“You have heard the challenge. What will you put on the record tonight?”',choices:e.stage===0?[{id:'record',title:'Defend your measurable record',detail:'Trust +2 if the issue score is at least 52; otherwise −2'},{id:'own',title:'Acknowledge the shortfall',detail:'Trust +1 · opposition momentum −2'},{id:'attack',title:'Challenge your opponent’s credibility',detail:'Capital +1 · trust −2'}]:[{id:'specific',title:'Commit to the published platform',detail:'Momentum −4 if at least two goals are on track; otherwise trust −1'},{id:'listen',title:'Promise to work across divisions',detail:'Trust +1 · momentum −1'}]};return {title:'The press conference',speaker:'Correspondent Jordan Ellis',question:e.stage===0?'“You promised results. What evidence can the public see today?”':e.answers[0]==='timeline'?'“Will you also publish missed deadlines and cost overruns?”':'“Are you claiming success before the results have arrived?”',choices:e.stage===0?[{id:'timeline',title:'Publish the implementation timeline',detail:'Trust +1 · a follow-up question on accountability'},{id:'victory',title:'Declare the program a success',detail:'Trust +2 with a completed project; otherwise −3'}]:[{id:'transparent',title:'Release the complete record',detail:'Trust +2 · momentum −2'},{id:'deflect',title:'Redirect the question to opponents',detail:'Capital +1 · trust −2 · momentum +2'}]};}
 function startEncounter(s,type){if(!allowed(s)||!['press','debate'].includes(type)||s.location!=='oval'||slots(s)<1||s.executive.encounters.some(e=>e.quarter===s.quarter))return fail('One media appearance per quarter requires an Oval Office appointment.');if(type==='debate'&&![7,15].includes(s.quarter))return fail('Debates take place in the final quarter before each election.');s.appointments.push({quarter:s.quarter,type:'media'});s.executive.encounters.push({type,quarter:s.quarter,stage:0,answers:[],done:false});return result('The cameras are live. Choose your answer, then handle the follow-up.');}
 function answerEncounter(s,choice){const e=s.executive.encounters.find(e=>e.quarter===s.quarter&&!e.done);if(!allowed(s)||!e||!encounterOptions(s,e).choices.some(x=>x.id===choice))return fail('That answer is unavailable.');let trust=0,momentum=0;if(choice==='record')trust=s.metrics[s.executive.opposition.issue]>=52?2:-2;if(choice==='own'){trust=1;momentum=-2;}if(choice==='attack'||choice==='deflect'){trust=-2;s.capital=limit(s.capital+1,0,20);momentum=choice==='deflect'?2:0;}if(choice==='specific'){if(legacy(s).goals.filter(g=>g.met).length>=2)momentum=-4;else trust=-1;}if(choice==='listen'){trust=1;momentum=-1;}if(choice==='timeline')trust=1;if(choice==='victory')trust=s.executive.bills.some(b=>b.progress>=100)?2:-3;if(choice==='transparent'){trust=2;momentum=-2;}s.metrics.trust=limit(s.metrics.trust+trust);s.executive.opposition.momentum=limit(s.executive.opposition.momentum+momentum);e.answers.push(choice);e.stage++;e.done=e.stage>=2;record(s,'media',e.type==='press'?'Press conference':'Presidential debate',`${choice}: trust ${trust>=0?'+':''}${trust}, opposition momentum ${momentum>=0?'+':''}${momentum}.`);return result(e.done?'Appearance complete. Your answers are in the presidential record.':'Answer recorded. The moderator has a follow-up.');}
 function legacy(s){const platform=s.executive.platform,goals=(platform?.goals||[]).map(id=>{const g=GOALS.find(x=>x.id===id),value=g.id==='debt'?s.debt:s.metrics[g.metric];return {...g,value:Math.round(value),met:g.id==='debt'?value<=g.target:value>=g.target};});const project=s.executive.bills.find(b=>b.id===platform?.signature);return {goals,project,kept:s.promises.filter(p=>p.status==='kept').length,broken:s.promises.filter(p=>p.status==='broken').length,completed:s.executive.bills.filter(b=>b.progress>=100).length};}
 function quarter(s,report){const x=s.executive;if(!x.platform)x.platform={goals:['housing','health','trust'],signature:'housing',chosen:s.quarter-1};
  for(const def of REGIONS){const r=x.regions[def.id];for(const k of ['housing','jobs','health','energy'])r[k]=limit(r[k]+(s.metrics[k]+def.offset[k]-r[k])*.12);r.goodwill*=.9;}
  for(const b of x.bills.filter(b=>b.status==='passed'&&b.progress<100)){const d=billDef(b.id),team=x.cabinet[d.sponsor],step=team.status==='resigned'?12:Math.round(18+team.competence*.2),gain=Math.min(step,100-b.progress);b.progress+=gain;const areas=b.amendments.includes('local')?REGIONS.map(r=>r.id):d.regions;for(const id of areas){const r=x.regions[id];if(d.metric in r)r[d.metric]=limit(r[d.metric]+gain*.09);r.jobs=limit(r.jobs+gain*.02);news(s,id,`${d.name}: ${b.progress}% delivered.`);}if(b.progress>=100){report.changes.push(`${d.name}: delivery complete.`);record(s,'delivery',d.name,'Construction and service rollout complete.');}if(b.id==='housing'&&b.progress>=50&&!b.amendments.includes('audit')&&!x.crises.some(c=>c.id==='contracts')){x.crises.push({id:'contracts',region:'coast',stage:'investigation',since:s.quarter,response:null});report.changes.push('Housing procurement contracts face an investigation.');}}
  for(const [id,p] of Object.entries(x.cabinet)){p.strain=s.relationships[id]<30?p.strain+1:0;if(p.strain===1&&p.status==='serving')report.changes.push(`${TEAM[id].portfolio}: your colleague publicly questions the administration. Repair the relationship before the next quarter.`);if(p.strain>=2&&p.status==='serving'){p.status='resigned';report.changes.push(`${TEAM[id].portfolio}: ${id==='chen'||id==='brooks'?'the secretary resigns':'your ally withdraws cooperation'}. Delivery slows until a replacement is appointed.`);record(s,'cabinet',TEAM[id].portfolio,'Support withdrawn after two quarters of strained relations.');}}
  for(const c of x.crises.filter(c=>c.stage!=='resolved'&&c.since<s.quarter)){const r=x.regions[c.region];if(c.stage==='warning'){c.damage=Math.max(2,13-s.levels.grid*2-(c.response==='prepare'?5:0));r.housing=limit(r.housing-c.damage);r.energy=limit(r.energy-c.damage);r.goodwill=limit(r.goodwill-2,-15,15);c.stage='landfall';report.changes.push(`The coastal storm makes landfall. Local housing and energy fall ${c.damage} points.`);news(s,c.region,`Storm damage: ${c.damage} points. Relief decisions are on the president’s desk.`);}else if(c.stage==='landfall'){if(!c.response){r.goodwill=limit(r.goodwill-5,-15,15);s.metrics.trust=limit(s.metrics.trust-3);report.changes.push('Delayed storm relief draws criticism from coastal governors.');}if(c.response==='full'&&s.levels.transparency<3){c.stage='investigation';report.changes.push('Emergency contracts trigger a procurement investigation.');}else{c.stage='resolved';report.changes.push('Coastal recovery moves to local agencies.');}}else{if(!c.response){s.metrics.trust=limit(s.metrics.trust-3);x.opposition.momentum=limit(x.opposition.momentum+5);}c.stage='resolved';report.changes.push(c.response==='publish'?'The procurement report is published; corrective work begins.':'The procurement controversy damages confidence in the administration.');}c.response=null;c.since=s.quarter;}
  if(s.quarter>=2&&!x.crises.some(c=>c.id==='storm')&&(s.quarter>=3||s.metrics.energy<50||s.metrics.climate<44)){x.crises.push({id:'storm',region:'coast',stage:'warning',since:s.quarter,response:null});report.changes.push('Storm watch issued for the coast. Preparation is available in the Situation Room.');}
  x.opposition.issue=['housing','health','jobs','trust'].sort((a,b)=>s.metrics[a]-s.metrics[b])[0];x.opposition.momentum=limit(x.opposition.momentum+(s.metrics[x.opposition.issue]<45?3:-1)+(s.debt>130?2:0));
  for(const e of x.encounters.filter(e=>!e.done&&e.quarter<s.quarter)){e.done=true;e.abandoned=true;s.metrics.trust=limit(s.metrics.trust-1);report.changes.push('An unfinished media appearance draws questions about transparency.');}
 }
 return {BLOCS,BILLS,AMENDMENTS,REGIONS,GOALS,TEAM,initialize,platform,propose,activeBill,votes,amend,lobby,vote,regionalView,election,regionalVisit,modifier,spending,staffFactor,teamAction,person,crisisOptions,respondCrisis,encounterOptions,startEncounter,answerEncounter,legacy,quarter};
})();
