const STORAGE='four-years-oval-prototype-v1';
let state=null,scene,camera,renderer,model,orbit,mode='walk',keys=new Set(),tapKeys=new Set(),drag=false,lastX=0,lastY=0,yaw=0,pitch=-.12,task=null,ready=false,toastTimer,currentLocation='oval',transitioning=false;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
let currentPage='command',selectedPolicy='clinic',lastReport=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qlabel=q=>q>=16?'End of Year 4':`Year ${Math.floor(q/4)+1} · Quarter ${q%4+1}`;
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function toast(message){const el=$('toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3400)}
function pct(value){return `${Math.round(value)}%`}
function signed(n){return `${n>=0?'+':''}${Math.round(n)}`}
function spark(value){return `<span class="meter"><i style="width:${clamp(value,0,100)}%"></i></span>`}
function stats(){const b=FourYearsSim.budget(state),p=FourYearsSim.poll(state);return [['Approval',p,'%'],['Political capital',state.capital,'/20'],['Budget',signed(b.balance),''],['Debt',Math.round(state.debt),'']].map(([name,v,unit])=>`<div class="stat ${Number(v)<0||name==='Approval'&&v<40?'warning':''}"><span>${name}</span><strong>${v}</strong><em>${unit}</em></div>`).join('')}
function timeline(){return `<div class="timeline" aria-label="${state.quarter} of 16 quarters completed">${Array.from({length:16},(_,i)=>`<div title="${qlabel(i)}" class="tick ${i<state.quarter?'done':i===state.quarter?'current':''}"></div>`).join('')}</div>`}
function tabs(){return `<div class="strategy-tabs">${[['command','Situation'],['policies','Policies'],['voters','Voters'],['budget','Budget'],['journal','Record']].map(([id,label])=>`<button data-tab="${id}" class="${currentPage===id?'selected':''}">${label}</button>`).join('')}</div>`}
function header(eyebrow,title,lede=''){return `<div class="eyebrow">${eyebrow}</div><h2>${title}</h2>${lede?`<p class="intro">${lede}</p>`:''}${timeline()}${tabs()}`}
function openPage(page){if(!state)return;currentPage=page;$('panel').hidden=false;update()}
function bindTabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openPage(b.dataset.tab))}
function update(){if(!state)return;$('stats').innerHTML=stats();$('date').textContent=state.ended?'The term is complete':qlabel(state.quarter);$('briefing').textContent=$('panel').hidden?'Open strategy':'Hide strategy';
 const page=state.ended&&currentPage==='command'?'ending':currentPage;
 ({command:renderCommand,policies:renderPolicies,voters:renderVoters,budget:renderBudget,journal:renderJournal,report:renderReport,ending:renderEnding}[page]||renderCommand)();bindTabs();}
function situationCard(name){return `<span class="situation">${esc(name)}</span>`}
function renderCommand(){const ev=FourYearsSim.AGENDA[state.quarter],b=FourYearsSim.budget(state),p=FourYearsSim.poll(state),chosen=state.agendaChoice!==null;
 $('panel').dataset.page='command';$('panel').innerHTML=header('THE SITUATION ROOM',chosen?'Decision filed':ev.title,chosen?'Your response is on the record. Adjustments to policy wait until the next quarter.':ev.body)+`<div class="overview-grid"><div><small>Election forecast</small><strong>${p}%</strong>${spark(p)}</div><div><small>Quarterly balance</small><strong class="${b.balance<0?'bad':''}">${signed(b.balance)}</strong><span class="tiny">revenue ${b.revenue} · spending ${b.spending}</span></div></div>${state.situations.length?`<div class="issue-list">${state.situations.map(situationCard).join('')}</div>`:'<p class="note">No active national crisis. Conditions can change as policies take effect.</p>'}<div class="rule"></div><div class="eyebrow">${chosen?'Next step':'Decision on your desk'}</div>${chosen?`<p class="paper">${esc(ev.choices[state.agendaChoice][0])}. Effects will appear in next quarter’s report.</p><button class="primary" id="advance-quarter">Advance to next quarter →</button>`:ev.choices.map((c,i)=>`<button class="choice" data-agenda="${i}"><strong>${esc(c[0])}</strong><small>Budget cost ${c[2]} · ${Object.entries(c[1]).map(([k,v])=>`${FourYearsSim.METRICS[k]} ${signed(v)}`).join(' · ')}</small></button>`).join('')}<p class="note">Policy changes use political capital. Their effects build over several quarters; each group weighs the results differently.</p>`;
 $('panel').querySelectorAll('[data-agenda]').forEach(btn=>btn.onclick=()=>{FourYearsSim.choose(state,Number(btn.dataset.agenda));save();update()});if($('advance-quarter'))$('advance-quarter').onclick=advanceQuarter;}
function advanceQuarter(){lastReport=FourYearsSim.advance(state);if(!lastReport)return;save();currentPage=state.ended?'ending':'report';update();}
function renderReport(){const r=lastReport;if(!r){currentPage='command';renderCommand();return}const b=r.budget;
 $('panel').dataset.page='report';$('panel').innerHTML=header('QUARTERLY INTELLIGENCE',qlabel(r.quarter),'The country responds to your decisions, spending, and policies already in motion.')+`<div class="overview-grid"><div><small>Polling</small><strong>${FourYearsSim.poll(state)}%</strong>${spark(FourYearsSim.poll(state))}</div><div><small>Budget balance</small><strong class="${b.balance<0?'bad':''}">${signed(b.balance)}</strong><span class="tiny">debt ${Math.round(state.debt)}</span></div></div>${r.election?`<p class="election-note">${r.election.type==='midterm'?(r.election.majority?'Your coalition keeps a legislative majority.':'Your coalition loses its legislative majority. Political capital falls.'):r.election.won?'You win another term.':'The voters choose a change in leadership.'} Vote: ${r.election.vote}%.</p>`:''}<div class="rule"></div><h3>What changed</h3>${r.changes.length?r.changes.map(x=>`<div class="logline">${esc(x)}</div>`).join(''):'<p class="note">No large changes this quarter. Policy effects may still be building.</p>'}${r.situations.length?`<h3>Active situations</h3><div class="issue-list">${r.situations.map(situationCard).join('')}</div>`:''}<div class="actions"><button class="primary" id="next-desk">${state.ended?'See election result':'Return to your desk'}</button><button class="secondary" id="report-policies">Policy atlas</button></div>`;
 $('next-desk').onclick=()=>openPage(state.ended?'ending':'command');$('report-policies').onclick=()=>openPage('policies');}
function renderPolicies(){const p=FourYearsSim.policy(selectedPolicy)||FourYearsSim.P[0],level=state.levels[p.id],implemented=state.implemented[p.id],b=FourYearsSim.budget(state),locked=state.agendaChoice!==null||state.ended;
 $('panel').dataset.page='policies';$('panel').innerHTML=header('POLICY ATLAS','Set the direction','Change a policy from 0 to 4. The full effect arrives over time, while budget commitments begin now.')+`<div class="policy-grid"><div class="policy-list">${FourYearsSim.P.map(x=>`<button class="policy-row ${x.id===p.id?'selected':''}" data-policy="${x.id}"><small>${x.department}</small><strong>${x.name}</strong><span>${state.levels[x.id]}/4</span></button>`).join('')}</div><div class="policy-detail"><div class="eyebrow">${p.department}</div><h3>${p.name}</h3><p class="note">Strength ${level}/4 · Implemented ${implemented.toFixed(1)}/4 · ${p.lag} quarter${p.lag===1?'':'s'} to settle</p><div class="level-control"><button id="less-policy" ${locked||level===0?'disabled':''} aria-label="Reduce ${p.name}">−</button><strong>${level} / 4</strong><button id="more-policy" ${locked||level===4?'disabled':''} aria-label="Increase ${p.name}">+</button></div><p class="note">An adjustment costs ${2+(p.lag>1?1:0)} capital per step. Current capital: ${state.capital}.</p><div class="rule"></div><div class="eyebrow">Causal links</div>${Object.entries(p.effects).map(([key,value])=>`<div class="impact"><span class="${value<0?'bad':'good'}">${value<0?'↘':'↗'}</span><span>${FourYearsSim.METRICS[key]}</span><strong>${signed(value)} / level</strong></div>`).join('')}<div class="impact"><span class="${p.cost>0?'bad':'good'}">${p.cost>0?'↘':'↗'}</span><span>${p.cost>0?'Spending':'Revenue'}</span><strong>${Math.abs(p.cost)} / level</strong></div><p class="note">Each link contributes to conditions, which shape voter approval and sometimes one another. Stronger policy can carry both benefits and costs.</p><div class="rule"></div><p>Current national balance: <strong class="${b.balance<0?'bad':''}">${signed(b.balance)}</strong></p></div></div>`;
 $('panel').querySelectorAll('[data-policy]').forEach(btn=>btn.onclick=()=>{selectedPolicy=btn.dataset.policy;renderPolicies();bindTabs()});for(const [id,delta] of [['less-policy',-1],['more-policy',1]])$(id).onclick=()=>{const result=FourYearsSim.changePolicy(state,p.id,level+delta);if(!result.ok)toast(result.reason);else{save();update()}};}
function renderVoters(){const groups=FourYearsSim.groups(state),p=FourYearsSim.poll(state);
 $('panel').dataset.page='voters';$('panel').innerHTML=header('ELECTORAL MAP','The electorate','Groups overlap in real life; here each profile represents a distinct voting bloc with its own priorities.')+`<div class="overview-grid"><div><small>Election forecast</small><strong>${p}%</strong>${spark(p)}</div><div><small>Next election</small><strong>${state.quarter<8?'Midterm':'General'}</strong><span class="tiny">${state.quarter<8?8-state.quarter:16-state.quarter} quarters away</span></div></div><p class="note">The forecast weights approval by group size and expected turnout. Policy stances and lived conditions both matter.</p>${groups.map(g=>`<div class="voter-card"><div class="voter-head"><strong>${g.name}</strong><strong class="${g.approval<45?'bad':''}">${g.approval}%</strong></div>${spark(g.approval)}<small>${g.share}% of electorate · ${g.turnout}% turnout · values ${Object.entries(g.priorities).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([k])=>FourYearsSim.METRICS[k].toLowerCase()).join(' and ')}</small><div class="tiny">Supports ${g.fav.map(id=>FourYearsSim.policy(id).name).join(', ')}${g.opp.length?` · opposes ${g.opp.map(id=>FourYearsSim.policy(id).name).join(', ')}`:''}</div></div>`).join('')}`;}
function renderBudget(){const b=FourYearsSim.budget(state),rows=FourYearsSim.P.map(p=>({p,amount:(state.levels[p.id]-2)*p.cost})).filter(x=>x.amount!==0).sort((a,b)=>Math.abs(b.amount)-Math.abs(a.amount));
 $('panel').dataset.page='budget';$('panel').innerHTML=header('THE TREASURY','Budget & debt','Figures are game units per quarter. A deficit adds to the debt, which then increases interest costs.')+`<div class="budget-total"><div><span>Revenue</span><strong>${b.revenue}</strong></div><div><span>Spending</span><strong>${b.spending}</strong></div><div><span>Balance</span><strong class="${b.balance<0?'bad':''}">${signed(b.balance)}</strong></div><div><span>Debt</span><strong>${Math.round(state.debt)}</strong></div></div><p class="note">Interest this quarter: ${b.interest}. Growth also affects receipts. The last agenda decision may add to debt.</p><div class="rule"></div><h3>Policy commitments</h3>${rows.length?rows.map(({p,amount})=>{const change=p.cost<0?-amount:amount;return `<div class="budget-row"><span>${p.name}</span><strong class="${p.cost<0?change>0?'good':'bad':change>0?'bad':'good'}">${p.cost<0?'Revenue':'Spending'} ${signed(change)}</strong></div>`}).join(''):'<p class="note">All policies are at their baseline settings.</p>'}<div class="rule"></div><button class="secondary" id="budget-policies">Adjust policies</button>`;$('budget-policies').onclick=()=>openPage('policies');}
function renderJournal(){const items=state.history.slice().reverse();$('panel').dataset.page='journal';$('panel').innerHTML=header('PRESIDENTIAL RECORD','Journal',`${items.length} entries across ${state.quarter} completed quarters.`)+`${items.length?items.map(h=>`<div class="logline"><small>${qlabel(h.quarter)} · ${esc(h.type)}</small><strong>${esc(h.title)}</strong><br>${esc(h.detail)}</div>`).join(''):'<p>No decisions yet.</p>'}${state.legacy?.history?.length?`<div class="rule"></div><h3>Earlier monthly briefings</h3>${state.legacy.history.slice().reverse().map(h=>`<div class="logline"><small>Month ${Number(h.month)+1}</small><strong>${esc(h.event)}</strong><br>${esc(h.choice)}</div>`).join('')}`:''}`;}
function renderEnding(){const vote=FourYearsSim.poll(state),won=vote>=50;$('panel').dataset.page='ending';$('panel').innerHTML=header('THE FOUR-YEAR RECORD',won?'Another term earned':'A change of leadership',won?'The voters have given you a new mandate. The choices of this term shaped that result.':'The voters chose a different direction after four years. The record of your administration remains.')+`<div class="overview-grid"><div><small>Final vote</small><strong>${vote}%</strong>${spark(vote)}</div><div><small>National debt</small><strong>${Math.round(state.debt)}</strong><span class="tiny">game units</span></div></div><p class="paper">${state.midterm?.majority?'Your coalition held':'Your coalition lost'} the midterm majority. ${state.history.filter(h=>h.type==='policy').length} policy changes and ${state.history.filter(h=>h.type==='agenda').length} agenda decisions shaped the term.</p><div class="actions"><button class="primary" id="new-term">Start a new game</button><button class="secondary" id="ending-journal">Read the record</button></div>`;$('new-term').onclick=()=>{state=FourYearsSim.fresh();lastReport=null;currentPage='command';save();changeLocation('oval');setMode('walk');update()};$('ending-journal').onclick=()=>openPage('journal');}
function updateBriefing(){openPage(state?.ended?'ending':'command')}
function start(continueSave){let old=null;try{old=continueSave?JSON.parse(localStorage.getItem(STORAGE)):null}catch{}if(old&&old.version!==2&&!localStorage.getItem('four-years-legacy-backup-v1'))localStorage.setItem('four-years-legacy-backup-v1',JSON.stringify(old));state=continueSave?FourYearsSim.migrate(old):FourYearsSim.fresh();if(!Number.isInteger(state.quarter)||state.quarter<0||state.quarter>16)state=FourYearsSim.fresh();save();$('start').hidden=true;currentPage='command';update();setMode('walk');changeLocation(state.location==='aircraft'?'aircraft':'oval')}
if(localStorage.getItem(STORAGE))$('continue').hidden=false;
$('begin').onclick=()=>start(false);$('continue').onclick=()=>start(true);
$('briefing').onclick=()=>{if(!state)return;if(!$('panel').hidden){$('panel').hidden=true;$('briefing').textContent='Open strategy'}else openPage(currentPage)};
$('journal').onclick=()=>openPage('journal');
$('policies').onclick=()=>openPage('policies');$('voters').onclick=()=>openPage('voters');$('budget').onclick=()=>openPage('budget');
