const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Sim=vm.runInNewContext(fs.readFileSync(__dirname+'/simulation-core.js','utf8')+'\nFourYearsSim');
const turn=s=>{assert.equal(Sim.choose(s,1),true);return Sim.advance(s)};
const s=Sim.fresh();
assert.equal(Sim.availableSlots(s),2);
assert.equal(Sim.meeting(s,'chen','promise').ok,true);
assert.equal(Sim.meeting(s,'chen','promise').ok,false,'no repeated meeting rewards');
assert.equal(Sim.meeting(s,'ruiz','listen').ok,true);
assert.equal(Sim.meeting(s,'bell','promise').ok,false,'two appointments only');
assert.equal(s.promises[0].policy,'housing');
assert.equal(Sim.changePolicy(s,'housing',3).ok,true);
const delivered=turn(s);
assert.equal(s.promises[0].status,'kept');
assert.ok(delivered.changes.some(x=>x.includes('Promise kept')));
assert.equal(s.relationships.chen,62);
assert.equal(Sim.availableSlots(s),2,'new quarter refreshes slots');

const broken=Sim.fresh();Sim.meeting(broken,'chen','promise');turn(broken);
assert.equal(broken.promises[0].status,'open');turn(broken);
assert.equal(broken.promises[0].status,'broken');
assert.equal(broken.relationships.chen,42);
assert.equal(broken.goodwill.workers,-3);
const extended=Sim.fresh();Sim.meeting(extended,'chen','promise');turn(extended);
assert.equal(Sim.meeting(extended,'chen','extend').ok,true);turn(extended);
assert.equal(extended.promises[0].status,'open');
assert.equal(Sim.meeting(extended,'chen','extend').ok,false,'one extension only');
turn(extended);assert.equal(extended.promises[0].status,'broken');

const traveler=Sim.fresh();
assert.equal(Sim.campaignTrip(traveler,'lakes','jobs','ruiz').ok,false,'no out-of-season campaign');
traveler.quarter=6;
assert.equal(Sim.campaignTrip(traveler,'lakes','jobs','ruiz').ok,false,'must board Air Force One');
assert.equal(Sim.meeting(traveler,'chen','listen').ok,true);
traveler.location='aircraft';
assert.equal(Sim.meeting(traveler,'bell','listen').ok,false,'Oval meetings require Oval location');
const before=Sim.groups(traveler).find(g=>g.id==='workers').approval;
assert.equal(Sim.campaignTrip(traveler,'lakes','jobs','ruiz').ok,true);
assert.equal(Sim.availableSlots(traveler),0,'travel competes with meetings');
assert.ok(Sim.groups(traveler).find(g=>g.id==='workers').approval>before);
assert.equal(Sim.campaignTrip(traveler,'coast','housing','chen').ok,false);
const boost=traveler.campaign.boosts.workers;turn(traveler);
assert.equal(traveler.campaign.boosts.workers,boost*.75);
assert.equal(Sim.campaignTrip(traveler,'plains','energy','ruiz').ok,true);
const election=turn(traveler);assert.equal(election.election.type,'midterm');
assert.equal(Sim.campaignSeason(traveler),false);

const old=Sim.fresh();old.version=2;old.quarter=7;old.location='aircraft';
for(const key of ['relationships','appointments','promises','goodwill','campaign'])delete old[key];
const migrated=Sim.migrate(JSON.parse(JSON.stringify(old)));
assert.equal(migrated.version,3);assert.equal(migrated.quarter,7);assert.equal(migrated.location,'aircraft');
assert.equal(Sim.availableSlots(migrated),2);
const late=Sim.fresh();late.quarter=15;Sim.meeting(late,'chen','compromise');
assert.equal(late.promises[0].due,16);turn(late);assert.equal(late.promises[0].status,'broken');
assert.equal(Sim.meeting(late,'bell','listen').ok,false);
console.log('Political life checks passed: appointment limits, promises, deadlines, migration, location gates, campaign effects and elections.');
